### ISSUE TITLE
demo-server stuck on exit on eglstream after screencopy

### ISSUE THREAD

**Issue by Saviq** [canonical/mir#2892]
On a 22.04 system with Nvidia, using eglstream:

```plain
$ sh -c 'sleep 5; WAYLAND_DISPLAY=wayland-0 grim' & mir-test-tools.demo-server
# wait 5s
^C
# stuck
```

`--devmode` doesn't fix, can't reproduce with plain `mir_demo_server` from `ppa:mir-team/dev`. Running under `--gdbserver` hides the problem. Gah.

```plain
$ snap info mir-test-tools | grep installed:
installed:          2.13.0+dev62-snap153            (11303) 84MB -
$ apt-cache policy mir-test-tools | grep '\*\*\*'
 *** 2.13.0+dev62-ge720163c52-0ubuntu22.04 500
```

**Comment by Saviq** [comment]
_Maybe_ some clue here, managed to `gdb -p` into it when stuck:

<details>
<summary>gdb.txt</summary>

```gdb
  Id   Target Id                                           Frame 
* 1    Thread 0x7f3392d8f700 (LWP 19769) "mir_demo_server" futex_wait (private=0, expected=2, futex_word=0x5622c0ec4350) at ../sysdeps/nptl/futex-internal.h:146
  2    Thread 0x7f3392aed640 (LWP 19804) "pool-spawner"    syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  3    Thread 0x7f33922ec640 (LWP 19805) "gmain"           0x00007f3393d7fd7f in __GI___poll (fds=0x5622c0ec54d0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  4    Thread 0x7f3391aeb640 (LWP 19806) "gdbus"           0x00007f3393d7fd7f in __GI___poll (fds=0x5622c0efde20, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7f3381bff640 (LWP 19807) "mir_demo_server" __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5622c10000c8)
    at ./nptl/futex-internal.c:57
  6    Thread 0x7f3380c15640 (LWP 19826) "EglStrmAcq*C3F1" __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5622c13bb6b8)
    at ./nptl/futex-internal.c:57
  7    Thread 0x7f3377657640 (LWP 19827) "mir_demo_server" __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5622c0f35810)
    at ./nptl/futex-internal.c:57
  8    Thread 0x7f3374c48640 (LWP 19830) "CPMMListener"    0x00007f3393d7fd7f in __GI___poll (fds=0x7f3374c3fe38, nfds=1, timeout=300000) at ../sysdeps/unix/sysv/linux/poll.c:29

Thread 8 (Thread 0x7f3374c48640 (LWP 19830) "CPMMListener"):
#0  0x00007f3393d7fd7f in __GI___poll (fds=0x7f3374c3fe38, nfds=1, timeout=300000) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f33829f1477 in ?? () from target:/var/lib/snapd/lib/gl/libnvidia-eglcore.so.515.105.01
#2  0x00007f33829efdda in ?? () from target:/var/lib/snapd/lib/gl/libnvidia-eglcore.so.515.105.01
#3  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#4  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7f3377657640 (LWP 19827) "mir_demo_server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5622c0f35810) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5622c0f35810) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5622c0f35810, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f3393cfaac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5622c0f357c0, cond=0x5622c0f357e8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5622c0f357e8, mutex=0x5622c0f357c0) at ./nptl/pthread_cond_wait.c:627
#5  0x00007f3393c3e2c1 in ?? () from target:/snap/mir-test-tools/11303/usr/lib/x86_64-linux-gnu/libmirplatform.so.25
#6  0x00007f3393f8b2b3 in ?? () from target:/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7f3380c15640 (LWP 19826) "EglStrmAcq*C3F1"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5622c13bb6b8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5622c13bb6b8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5622c13bb6b8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f3393cfaac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5622c0ef57b0, cond=0x5622c13bb690) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5622c13bb690, mutex=0x5622c0ef57b0) at ./nptl/pthread_cond_wait.c:627
#5  0x00007f3390eb8da8 in ?? () from target:/var/lib/snapd/lib/gl/libEGL_nvidia.so.0
#6  0x00007f3390e84fa8 in ?? () from target:/var/lib/snapd/lib/gl/libEGL_nvidia.so.0
#7  0x00007f3390ebeade in ?? () from target:/var/lib/snapd/lib/gl/libEGL_nvidia.so.0
#8  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#9  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7f3381bff640 (LWP 19807) "mir_demo_server"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x5622c10000c8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x5622c10000c8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x5622c10000c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f3393cfaac1 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5622c1000078, cond=0x5622c10000a0) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x5622c10000a0, mutex=0x5622c1000078) at ./nptl/pthread_cond_wait.c:627
#5  0x00007f3392d6f8c5 in ?? () from target:/snap/mir-test-tools/11303/usr/lib/x86_64-linux-gnu/mir/server-platform/graphics-eglstream-kms.so.20
#6  0x00007f3393f8b2b3 in ?? () from target:/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7f3391aeb640 (LWP 19806) "gdbus"):
#0  0x00007f3393d7fd7f in __GI___poll (fds=0x5622c0efde20, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f33938fe666 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f33938a92b3 in g_main_loop_run () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f3393b0304a in ?? () from target:/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f33938d8a51 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7f33922ec640 (LWP 19805) "gmain"):
#0  0x00007f3393d7fd7f in __GI___poll (fds=0x5622c0ec54d0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f33938fe666 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f33938a73e3 in g_main_context_iteration () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f33938a7431 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f33938d8a51 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7f3392aed640 (LWP 19804) "pool-spawner"):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f33938f81d3 in g_cond_wait () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f33938793fb in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f33938da67a in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f33938d8a51 in ?? () from target:/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f3393cfbb43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#6  0x00007f3393d8da00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f3392d8f700 (LWP 19769) "mir_demo_server"):
#0  futex_wait (private=0, expected=2, futex_word=0x5622c0ec4350) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x5622c0ec4350, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007f3393cff082 in lll_mutex_lock_optimized (mutex=0x5622c0ec4350) at ./nptl/pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x5622c0ec4350) at ./nptl/pthread_mutex_lock.c:93
#4  0x00007f33942b8b98 in __gthread_mutex_lock (__mutex=0x5622c0ec4350) at /usr/include/x86_64-linux-gnu/c++/11/bits/gthr-default.h:749
#5  std::mutex::lock (this=0x5622c0ec4350) at /usr/include/c++/11/bits/std_mutex.h:100
#6  std::lock_guard<std::mutex>::lock_guard (__m=..., this=<optimized out>, this=<optimized out>, __m=...) at /usr/include/c++/11/bits/std_mutex.h:229
#7  mir::frontend::WaylandExecutor::State::enqueue_termination(std::function<void ()>&&) (terminator=..., this=0x5622c0ec4350) at frontend_wayland/./src/server/frontend_wayland/wayland_executor.cpp:86
#8  mir::frontend::WaylandExecutor::~WaylandExecutor (this=<optimized out>, this=<optimized out>) at frontend_wayland/./src/server/frontend_wayland/wayland_executor.cpp:314
#9  0x00007f339422fb0a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5622c197c170) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#10 0x00007f33942ecd77 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#11 std::__shared_ptr<mir::Executor, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#12 std::shared_ptr<mir::Executor>::~shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr.h:122
#13 (anonymous namespace)::ErrorNotifyingRWMappableBuffer::~ErrorNotifyingRWMappableBuffer (this=<optimized out>, this=<optimized out>) at frontend_wayland/./src/server/frontend_wayland/shm.cpp:55
#14 std::destroy_at<(anonymous namespace)::ErrorNotifyingRWMappableBuffer> (__location=0x7f335c007420) at /usr/include/c++/11/bits/stl_construct.h:88
#15 std::allocator_traits<std::allocator<(anonymous namespace)::ErrorNotifyingRWMappableBuffer> >::destroy<(anonymous namespace)::ErrorNotifyingRWMappableBuffer> (__p=0x7f335c007420, __a=...) at /usr/include/c++/11/bits/alloc_traits.h:537
#16 std::_Sp_counted_ptr_inplace<(anonymous namespace)::ErrorNotifyingRWMappableBuffer, std::allocator<(anonymous namespace)::ErrorNotifyingRWMappableBuffer>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7f335c007410) at /usr/include/c++/11/bits/shared_ptr_base.h:528
#17 0x00007f339422fb0a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f335c007410) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#18 0x00007f33942eae52 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#19 std::__shared_ptr<mir::Executor, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#20 std::shared_ptr<mir::Executor>::~shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr.h:122
#21 ~<lambda> (this=<optimized out>, this=<optimized out>) at frontend_wayland/./src/server/frontend_wayland/wl_surface.cpp:337
#22 std::_Function_base::_Base_manager<mir::frontend::WlSurface::commit(const mir::frontend::WlSurfaceState&)::<lambda()> >::_M_destroy (__victim=...) at /usr/include/c++/11/bits/std_function.h:175
#23 std::_Function_base::_Base_manager<mir::frontend::WlrScreencopyFrameV1::prepare_target(wl_resource*)::<lambda(auto:16*)>::<lambda()> >::_M_manager (__op=<optimized out>, __source=..., __dest=...) at /usr/include/c++/11/bits/std_function.h:203
#24 std::_Function_handler<void(), mir::frontend::WlrScreencopyFrameV1::prepare_target(wl_resource*)::<lambda(auto:16*)>::<lambda()> >::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=<optimized out>) at /usr/include/c++/11/bits/std_function.h:282
#25 0x00007f339434d9de in std::_Function_base::~_Function_base (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/std_function.h:244
#26 std::function<void ()>::~function() (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/std_function.h:334
#27 std::destroy_at<std::function<void ()> >(std::function<void ()>*) (__location=0x5622c1011c70) at /usr/include/c++/11/bits/stl_construct.h:88
#28 std::_Destroy<std::function<void ()> >(std::function<void ()>*) (__pointer=0x5622c1011c70) at /usr/include/c++/11/bits/stl_construct.h:149
#29 std::_Destroy_aux<false>::__destroy<std::function<void ()>*>(std::function<void ()>*, std::function<void ()>*) (__last=<optimized out>, __first=0x5622c1011c70) at /usr/include/c++/11/bits/stl_construct.h:163
#30 std::_Destroy<std::function<void ()>*>(std::function<void ()>*, std::function<void ()>*) (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/11/bits/stl_construct.h:196
#31 std::_Destroy<std::function<void ()>*, std::function<void ()> >(std::function<void ()>*, std::function<void ()>*, std::allocator<std::function<void ()> >&) (__last=0x5622c1011c90, __first=<optimized out>) at /usr/include/c++/11/bits/alloc_traits.h:848
#32 std::deque<std::function<void ()>, std::allocator<std::function<void ()> > >::_M_destroy_data_aux(std::_Deque_iterator<std::function<void ()>, std::function<void ()>&, std::function<void ()>*>, std::_Deque_iterator<std::function<void ()>, std::function<void ()>&, std::function<void ()>*>) [clone .constprop.0] (__first=..., __last=..., this=<optimized out>) at /usr/include/c++/11/bits/deque.tcc:875
#33 0x00007f33942b5d0d in std::deque<std::function<void ()>, std::allocator<std::function<void ()> > >::_M_destroy_data(std::_Deque_iterator<std::function<void ()>, std::function<void ()>&, std::function<void ()>*>, std::_Deque_iterator<std::function<void ()>, std::function<void ()>&, std::function<void ()>*>, std::allocator<std::function<void ()> > const&) (this=0x5622c0ec4388, __last=..., __first=...) at /usr/include/c++/11/bits/stl_deque.h:2048
#34 std::deque<std::function<void ()>, std::allocator<std::function<void ()> > >::_M_erase_at_end(std::_Deque_iterator<std::function<void ()>, std::function<void ()>&, std::function<void ()>*>) (__pos=..., this=0x5622c0ec4388) at /usr/include/c++/11/bits/stl_deque.h:2065
#35 std::deque<std::function<void ()>, std::allocator<std::function<void ()> > >::clear() (this=0x5622c0ec4388) at /usr/include/c++/11/bits/stl_deque.h:1793
#36 mir::frontend::WaylandExecutor::State::drain (this=0x5622c0ec4350) at frontend_wayland/./src/server/frontend_wayland/wayland_executor.cpp:126
#37 (anonymous namespace)::EventLoopDestroyedHandler::on_destroyed (listener=0x5622c2acaab8) at frontend_wayland/./src/server/frontend_wayland/wayland_executor.cpp:190
#38 0x00007f33936bd269 in wl_event_loop_destroy () from target:/snap/mir-test-tools/11303/graphics/lib/x86_64-linux-gnu/libwayland-server.so.0
#39 0x00007f33936bf812 in wl_display_destroy () from target:/snap/mir-test-tools/11303/graphics/lib/x86_64-linux-gnu/libwayland-server.so.0
#40 0x00007f33942b2c28 in std::unique_ptr<wl_display, void (*)(wl_display*)>::~unique_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/move.h:104
#41 mir::frontend::WaylandConnector::~WaylandConnector (this=<optimized out>, this=<optimized out>) at frontend_wayland/./src/server/frontend_wayland/wayland_connector.cpp:386
#42 0x00007f339422fb0a in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x5622c2aca950) at /usr/include/c++/11/bits/shared_ptr_base.h:168
#43 0x00007f3394233c0f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:705
#44 std::__shared_ptr<mir::frontend::Connector, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1154
#45 std::shared_ptr<mir::frontend::Connector>::~shared_ptr (this=<optimized out>, this=<optimized out>) at /usr/include/c++/11/bits/shared_ptr.h:122
#46 mir::DisplayServer::Private::~Private (this=<optimized out>, this=<optimized out>) at ./src/server/display_server.cpp:71
#47 mir::DisplayServer::~DisplayServer (this=<optimized out>, this=<optimized out>) at ./src/server/display_server.cpp:224
#48 0x00007f33942346a0 in mir::run_mir(mir::ServerConfiguration&, std::function<void (mir::DisplayServer&)>, std::function<void (int)> const&) (config=..., init=..., terminator_=...) at ./src/server/run_mir.cpp:285
#49 0x00007f339423fe57 in mir::Server::run (this=0x5622c0ea4900) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#50 0x00007f339444ba12 in miral::MirRunner::Self::run_with(std::initializer_list<std::function<void (mir::Server&)> >) (options=..., this=0x5622c0ea2150) at ./src/miral/runner.cpp:167
#51 miral::MirRunner::run_with(std::initializer_list<std::function<void (mir::Server&)> >) (this=<optimized out>, options=...) at ./src/miral/runner.cpp:238
#52 0x00005622c050ec18 in ?? ()
#53 0x00007f3393c90d90 in __libc_start_call_main (main=main@entry=0x5622c050e5a0, argc=argc@entry=1, argv=argv@entry=0x7ffe1790b178) at ../sysdeps/nptl/libc_start_call_main.h:58
#54 0x00007f3393c90e40 in __libc_start_main_impl (main=0x5622c050e5a0, argc=1, argv=0x7ffe1790b178, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe1790b168) at ../csu/libc-start.c:392
#55 0x00005622c050f005 in ?? ()
```

</details>
